"""Initial migration

Revision ID: 677597d2ae3e
Revises: 
Create Date: 2024-11-19 22:17:43.897672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677597d2ae3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
